### ISSUE TITLE
Add dashboard logo

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#115]
For better recognition of the extension, add an icon to the XAR

**Comment by joewiz** [comment]
Nice that the icon you added in https://github.com/eXist-db/messaging-replication/commit/3c9db5b is public domain: https://commons.wikimedia.org/wiki/File:StarNetwork.svg.

**Comment by joewiz** [comment]
This can be closed now, right? Or were you hoping to find a different logo?

**Comment by dizzzz** [comment]
right you are :-) fixed with https://github.com/eXist-db/messaging-replication/commit/7560be9534c465d501d5a60c4a542bf373a50b37
