### ISSUE TITLE
warning: old data directory

### ISSUE THREAD

**Issue by ingoma** [eXist-db/messaging-replication#16]
the startup-log of exist (dev-branch, 20140130) provides the following info:

Information: Warning: package uses old-style content dir: '/my/data/dir/expathrepo/jms-lib-0.5/jms-lib'

**Comment by dizzzz** [comment]
yes, i have seen it. Well I consider Warnings not as a problem :-) I'll check with @wolfgangmm what is going on because the application has been generated by exude.

**Comment by dizzzz** [comment]
"This is coming from the expath library. It is just an info."
