### ISSUE TITLE
emphasize installation of package

### ISSUE THREAD

**Issue by ingoma** [eXist-db/messaging-replication#17]
to be honest, I experimented without success for while, until I recognized, that message replication has to be installed as a package at first! :smile: 

You should mention that in every doc/howto. Please emphasize the preferred way! I guess via exist's dashboard package manager.

**Comment by dizzzz** [comment]
thnx for the feedback I'll add a install page

**Comment by dizzzz** [comment]
Done https://github.com/eXist-db/messaging-replication/wiki/Installation
