### ISSUE TITLE
wiki: from 3000 to 1010

### ISSUE THREAD

**Issue by ingoma** [eXist-db/messaging-replication#18]
I suggest to change the second line in the sample

<pre>
let $doc := <doc>just some data</doc>
for $i in (1000 to 3000)
return
    xmldb:store('/db/replicated', concat('mydoc', $i , ".xml"), $doc)
</pre>

to

<pre>
for $i in (1000 to 1010)
</pre>

because ten sample docs are enough. And it can be quite tricky to get rid of 2000 docs in dashbord.

It might be helpfull to add the following lines:

<pre>
for $i in (1000 to 1010)
return
    xmldb:remove('/db/replicated/', concat('mydoc', $i , ".xml"))
</pre>

which produces ten additional messages and demonstrates the magic of replicated deletion.

**Comment by dizzzz** [comment]
right you are :-)

Actually this code I have used to do some performance measurements for the extension, used for the XML prague conference last year.

I'll update the numbers, and will add true remove code as well. Thnx

**Comment by dizzzz** [comment]
done, see https://github.com/eXist-db/messaging-replication/wiki/Document-replication
