### ISSUE TITLE
Message not readable

### ISSUE THREAD

**Issue by ingoma** [eXist-db/messaging-replication#19]
When I am in _Home_ -> _Manage Receivers_, I see in Column _E_ a number, which is a link.

While On Mouse over, a InfoBox appears, but it isn't readable. The text is behind the right border of the browser window.

I am using Firefox 24.1.0

**Comment by dizzzz** [comment]
You Can click in the (i) information symbol no? The mouse over can indeed be a bit unreadable I'll remove that fuctionality

**Comment by dizzzz** [comment]
since it was too condensed, it has been removed. Access via the (i) symbol
