### ISSUE TITLE
Receivers not deleted or not removed from the list

### ISSUE THREAD

**Issue by ingoma** [eXist-db/messaging-replication#20]
In _Home_ -> _Manage Receivers_ -> _JMS Manager_:
- As I clicked on delete receiver icon, the receiver disapperad from the list.
- But after _Refresh_ all receivers showed up again.
- A lick on info-icon shows:
  <pre> 
  exerr:ERROR No receiver exists for id '1' [at line 47, column 24, source: /db/apps/messaging-replication/modules/app.xql]
  </pre>

It's not clear whether the recievers are closed.

**Comment by ingoma** [comment]
After restart of eXist, all receivers are still in the list.

A click on info-icon shows:

<pre>
exerr:ERROR Permission denied, user 'jms' must be a DBA or be in group 'guest' [at line 47, column 24, source: /db/apps/messaging-replication/modules/app.xql]
</pre>

**Comment by ingoma** [comment]
I logged in into dashboard as admin. The knwon message from post #1 still appears:

<pre>
exerr:ERROR No receiver exists for id '1' [at line 47, column 24, source: /db/apps/messaging-replication/modules/app.xql]
</pre>

So far my investigation ...

**Comment by dizzzz** [comment]
If after a restart all receivers are still there, that you have a caching issue in your browser. I don;t have a solution yet for preventing caching the pages yet,,,,,,

the "exerr:ERROR No receiver exists for id '1'" is certainly caused by that, please do a 'shift-reload' in your browser.

**Comment by ingoma** [comment]
Forcing reload with ctrl-F5 helped.
