### ISSUE TITLE
owner/group/perms not replicated

### ISSUE THREAD

**Issue by phattire** [eXist-db/messaging-replication#40]
When saving a resource on the master, any change to owner/group/perms do
not get replicated to the slaves.

eXist 2.1
ActiveMQ 5.9.1
exist-messaging-replication 0.7.4

**Comment by dizzzz** [comment]
Started development ....

**Comment by dizzzz** [comment]
please verify the use case: 
- on mastere a stored resource the owner/group/perms is changed
- the change is not replicated to the slaves 

The update metadata trigger is not called at all, so the mechanism can't work anyway :-(
Work around: store document again completely with new perms

logged case: https://github.com/eXist-db/exist/issues/250 
work: https://github.com/eXist-db/messaging-replication/pull/41

**Comment by dizzzz** [comment]
Cant fix it right now, change required in exist-core

**Comment by dizzzz** [comment]
In the upcoming version, document metadata is replicated.
Replication of changes in Collection metadata is still a problem, there are no triggers for that. Implementing this is a problem.
To work around I added `replication:sync()` and `replication:sync-metadata()` functions.

**Comment by dizzzz** [comment]
implemented with https://github.com/eXist-db/messaging-replication/pull/76

**Comment by dizzzz** [comment]
consider it fixed
