### ISSUE TITLE
Create user/groups when not yet existing

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#78]
To make replication a bit more robust: create non-existing usernames/groups when required.
The user should have a non-accessible password

**Comment by ljo** [comment]
Nice. But isn't it the UIDs/GIDs that are used? They are sometimes already occupied in a few of my usecases. Can we provide a mapping?

**Comment by dizzzz** [comment]
actually the textual representation (the names) of the user/group are synced...

**Comment by ljo** [comment]
OK. so then IDs are just looked up for the logging.
